---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_URI: AgCjREh6+Ytew2UBE0IsMuNOv2ZogMd9nzavwbkUdEr3nOI39NFpxc1kDrLndMy/6Hf2sRtSqtjNZYpQsUs5RKVTXxYgYpfjaSksgUBc5rDU5OUVGpTUu7NyzeoXs0p6FXiStjmwzNuHllJtVxre0+ZK5C0/+Q+2RVOiZFQ5rzVCal/g5sSMtOtqflXv37bLG1ukjQRVaSJ6ZxmhEN3W7o7gfRdIUaldUc8mD5pBhJloKbD52FtZ1fRFVKzIBrw9Q9usZeQm1Ktr7B7lMXg8wUBRehlrXPxNQv89IenY8hSqvVR+npW4OlAXOXyke/ACkk0DN39EeNAB+NJtapjOsms5JyakN5xGSqLFRjRjax8OdQoBFaD9s5LRW2+CYMS1vD/0tn3y7ObDluGVgiRFVmPWakZGCKJn/y00uobh1eDS2RndIgS480PX0bhfNEpowPOjhILyiar0NaqRvLjugP7bPcdCJ3dQuSP6q9ZsL/GrmPCZAhhehkjQJY/ei4m2wDB/TTKMNOVek6fh5i6edgUv38Tcn5jatomZGXxfBhYIGXYE43o5cadCB7hJtwFWY6JHiE+p5HQg7v4W6Kws1uI9wjigBlzEZdDdGSJM98AW3QtCMT0+QB/o19eAGVtjbJhv4gO51o+4UKsasdGF06a+nctRUDdr3Y+9aUH61qtMwlgszMIsaYXjBdj6/Xyz87eLwnV2AsfD2lrsEoTqjc/au2ZwkS5kNsQvOCtYPaDjXlWhQ9xTLbTddhPhfdJQq6VeByDagBn/A+Jr5uZ2jo1mC7yR5w==
  template:
    metadata:
      name: backend-secrets
      namespace: default
