apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:	
            - labelSelector:	
                matchLabels:	
                  app: frontend	
              topologyKey: topology.kubernetes.io/zone
      containers:
        - name: frontend
          image: gauris17/wanderblog-frontend:v1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: frontend-config
