---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgB3jvNxqQ21PdSXn/7K3+Y3YI1e/wi7//C0Uqzr1rbEm9Vutpc6ECOqJZ3NRXxzGK37FUL5cPurVq9xryp5GYieY/5C40Xyzce4muTvZaNVqUDt33Lmy1Ec8L8E7+eZbg4y1QkcRKqsJoiuS1UG8KwoBWNZYes9kLoZ0H344dErkejMzLPj5KTADmzo5jd+4Zr+60j6Cvl44duTNhted0qFpwyHAER6JlujZiAWlzez3dW/ZBoYplTAlvdgjhcS/N13J+UfEMPDuiO/4eFH1ypL7jTAKq38Etqdy2irhdTIR+yjOkwI2u2nu+EKQwz7HuCIvqB/bJqlP2oxZFH7ksNlNB5RDeHzSn5EpYdxiQn7vc2dLGSPsjKf58BYNk6Rms1eiUrpLGLsYrzsNEED3MqfJkwaW1jYAmagE/xjhSdK7k6ZC7z1ghyDur7x+n6Bmd1wX4J4OOc3R0/0hzL1pZZeugHm3/rX0AKcaVCprmgfXOCrxNLJDv3NRYazv23O1oubDhbiu7uSxG92/WWu0Q33KDcEjZjNFK45uDE4iO3paRXfLN+hbJ5M4W+xXyCUgk4aVs9lQQWwI4ak20Ixk2LtDsjXCnyPHHWh9egSyucbhe1BkWrnDOYEM/myfJ14FMlURxx+Cs6byUcwVe6e+ZmJPbA8uQe4W5Duvp+6mYmOMi2gkgo/bACcsQdHATqhD7sgMu/fNK0Y7b54
    MONGO_INITDB_ROOT_USERNAME: AgCOEhlpeZcmmFexWAaxUdS010jZE2FZ3Bj2fVF64bjYfetmlLFN4redUaFaTWNL6tHntm94jL4VzSbWHF167k71zuWOE87MsAm2MHi2LifO+hRHu0wXvos8zCdl5paTomePVPZNZk+4UWjfoPOkiYSl4CEKEqEmek8jmRNLqnLbjadxAufcHSpBu0STEc9MFCF1YmN+FEKwwfwg6PGFI2ZmQrY0A8oJs5TWpsgyJ1QYhHC+y1UcRGlFt8u3KtJbHkkjhhamfSiGAAGX2R8aSVNPBHpKqW8985cra0G8LFZGB0abgIn6wZseRmuoK6HyV7XpfUqbntec4au8bOqgSCWEYUIFtzZeNbttEq3rX4/4LyFJyY5UZnlhazWsZ1Dohb038cvRGpl2DGfDtAgtP3UeTlEf1lF8IvBoo9vGj2VWEeYKyPf54J06gChU/cQAPLIfemb4f4UEKaS4V+ckJQ6WeVhpXOiSoOPry8kvRKxtEDBCvOtTTQhd8tMgx/NLAsFUrNHdr+8QxZxOlniTUJ8oTpZaDcwja7W0PzELNnAPqBowfPU6FBkalCWHtNm+k1ccp7qCMn+XSfjptGg7WLcZsWpFGUwoBrLBlvLrnNXkxPlfLaWBmB/2chZQ1VcZ2qY3f9PZyu3Lxg3MTv9xI3YPhA6Xc+m37FSyxOvRnA3k3I4KSKBWYD3DiF68kdt0nt3XERYUOA==
  template:
    metadata:
      name: mongo-secrets
      namespace: default
